version: 0.0
os: windows
files:
  - source: \test.html
    destination: c:\inetpub\wwwroot\demo\demo
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
